version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 12.16.1
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run: yarn lint
      - run: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test
